-- Development schema source for public-review reporting.
-- Replit Publish diffs this development schema to production; this file is
-- intentionally not executed by the application server or deployment build.
CREATE TABLE IF NOT EXISTS mall_review_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id bigint NOT NULL REFERENCES mall_reviews(id) ON DELETE CASCADE,
  reason varchar(32) NOT NULL CHECK (reason IN ('offensive', 'misleading', 'personal_data')),
  reporter_hash varchar(64) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (review_id, reporter_hash)
);

CREATE INDEX IF NOT EXISTS mall_review_reports_review_id_idx
  ON mall_review_reports (review_id);

CREATE INDEX IF NOT EXISTS mall_review_reports_reporter_created_at_idx
  ON mall_review_reports (reporter_hash, created_at);